// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d70c92fedde5513a7afa58bc7880dcaabd2c3d91/gulp-html-replace/gulp-html-replace.d.ts
declare module "gulp-html-replace" {
  interface AdvancedTask {
    src: string | string[];
    tpl: string;
  }

  interface Tasks {
    [taskId: string] : string | string[] | AdvancedTask;
  }

  interface Options {
    keepUnassigned?: boolean;
    keepBlockTags?: boolean;
    resolvePaths?: boolean;
  }

  interface HtmlReplace {
    (tasks: Tasks, options?: Options) : NodeJS.ReadWriteStream;
  }

  const htmlReplace : HtmlReplace;
  export = htmlReplace;
}
